In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('student_dataset.csv')

In [3]:
df.head()

,Country_of_Origin,Education_Level,Field_of_Study,Language_Proficiency,Visa_Type,Gender,University_Ranking,Region_of_Study,Age,Years_Since_Graduation,GPA,Internship_Experience,Employment_Status,Salary,Job_Sector
0,Vietnam,Bachelor's,IT,Fluent,Permanent Residency,Female,Low,EU,23,8,3.76,Yes,Employed,54397,Healthcare
1,Germany,Master's,Arts,Intermediate,Post-study,Male,High,UK,38,9,3.76,No,Employed,69635,Finance
2,Brazil,PhD,Engineering,Intermediate,Post-study,Male,High,Canada,23,2,3.52,Yes,Employed,96216,Finance
3,Vietnam,PhD,Health,Fluent,Post-study,Female,Medium,Australia,25,5,3.28,Yes,Employed,86076,Other
4,Nigeria,PhD,Engineering,Basic,Student,Male,High,Canada,24,2,3.01,Yes,Employed,82772,Finance

In [4]:
df.isnull().sum()

Country_of_Origin              0
Education_Level                0
Field_of_Study                 0
Language_Proficiency           0
Visa_Type                      0
Gender                         0
University_Ranking             0
Region_of_Study                0
Age                            0
Years_Since_Graduation         0
GPA                            0
Internship_Experience          0
Employment_Status              0
Salary                         0
Job_Sector                143356
dtype: int64

In [5]:
df[df["Job_Sector"].isnull()]["Employment_Status"].value_counts() #checking the cause of null job sector

Employment_Status
Continuing Education    74617
Unemployed              68739
Name: count, dtype: int64

In [6]:
df["Job_Sector"] = df["Job_Sector"].fillna("Not Specified")

In [7]:
df.loc[
    df["Job_Sector"].isnull() &
    (df["Employment_Status"] != "Employed"),
    "Job_Sector"
] = "Not Applicable"

In [8]:
df.duplicated().sum()

np.int64(3)

In [9]:
df = df.drop_duplicates()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 299997 entries, 0 to 299999
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Country_of_Origin       299997 non-null  object
 1   Education_Level         299997 non-null  object
 2   Field_of_Study          299997 non-null  object
 3   Language_Proficiency    299997 non-null  object
 4   Visa_Type               299997 non-null  object
 5   Gender                  299997 non-null  object
 6   University_Ranking      299997 non-null  object
 7   Region_of_Study         299997 non-null  object
 8   Age                     299997 non-null  int64
 9   Years_Since_Graduation  299997 non-null  int64
 10  GPA                     299997 non-null  float64
 11  Internship_Experience   299997 non-null  object
 12  Employment_Status       299997 non-null  object
 13  Salary                  299997 non-null  int64
 14  Job_Sector              299997 non-null  object
dtypes: float64(1), int64(3), object(11)
memory usage: 36.6+ MB

In [11]:
for col in df.select_dtypes(include='object'):
    print(col)
    print(df[col].value_counts().head(10))
    print("------")

Country_of_Origin
Country_of_Origin
Brazil      37751
China       37728
Germany     37510
Pakistan    37470
USA         37464
India       37464
Vietnam     37432
Nigeria     37178
Name: count, dtype: int64
------
Education_Level
Education_Level
Bachelor's    120141
Master's      105023
PhD            44858
Diploma        29975
Name: count, dtype: int64
------
Field_of_Study
Field_of_Study
Arts               50143
Engineering        50097
IT                 50091
Health             49931
Social Sciences    49916
Business           49819
Name: count, dtype: int64
------
Language_Proficiency
Language_Proficiency
Intermediate    90131
Advanced        90111
Basic           59881
Fluent          59874
Name: count, dtype: int64
------
Visa_Type
Visa_Type
Student                119752
Post-study              90339
Work Visa               59834
Permanent Residency     30072
Name: count, dtype: int64
------
Gender
Gender
Male      143888
Female    143849
Other      12260
Name: count, dtype: int64
------
University_Ranking
University_Ranking
Medium    149845
High       90580
Low        59572
Name: count, dtype: int64
------
Region_of_Study
Region_of_Study
Australia    75233
EU           74966
Canada       74900
UK           74898
Name: count, dtype: int64
------
Internship_Experience
Internship_Experience
Yes    194708
No     105289
Name: count, dtype: int64
------
Employment_Status
Employment_Status
Employed                156644
Continuing Education     74615
Unemployed               68738
Name: count, dtype: int64
------
Job_Sector
Job_Sector
Not Specified    143353
IT                19716
Education         19711
Other             19699
Healthcare        19666
Engineering       19590
Retail            19467
Consulting        19457
Finance           19338
Name: count, dtype: int64
------

In [12]:
df["Gender"] = df["Gender"].str.strip().str.title()

In [13]:
df["Salary"].describe()

count    299997.000000
mean      30333.995723
std       31791.223177
min           0.000000
25%           0.000000
50%       32298.000000
75%       56634.000000
max      118115.000000
Name: Salary, dtype: float64

In [14]:
df[df["Salary"] == 0]["Employment_Status"].value_counts()

Employment_Status
Continuing Education    74615
Unemployed              68738
Name: count, dtype: int64

In [16]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[20,25,30,35,40],
    labels=["20-25","26-30","31-35","36-40"]
)

df["GPA_Category"] = pd.cut(
    df["GPA"],
    bins=[0,2.5,3.0,3.5,4.0,5.0],
    labels=["Low","Average","Good","Very Good","Excellent"]
)

In [17]:
df.to_csv("cleaned_dataset.csv", index=False)

In [19]:
import os
os.listdir()

['.config', 'student_dataset.csv', 'cleaned_dataset.csv', 'sample_data']

In [20]:
from google.colab import files
files.download("cleaned_dataset.csv")